name: Run Script

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  refresh_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the full repo is cloned

      - name: Debug file paths
        run: ls -r  # List all files to check if requirements.txt exists


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt  # Install necessary Python libraries
  
      - name: Test DNS resolution
        run: |
          nslookup api.dropboxapi.com

      - name: Test connectivity with curl
        run: |
          curl -I https://api.dropboxapi.com
          
      #- name: Test internet acces
       # run: |
        #   ping -c 3 api.dropboxapi.com
         #  curl -I https://api.dropboxapi.co

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE }}  # Use the JSON key from GitHub Secrets
          
      - name: Run Python Script
        env:
          ACCOUNTS:  ${{ secrets.ACCOUNTS }}
          SENDER:  ${{ secrets.SENDER }}
          SENDER_CREDS:  ${{ secrets.SENDER_CREDS }}
          DROPBOX_APP_KEY:  ${{ secrets.DROPBOX_APP_KEY }}}
          DROPBOX_APP_SECRET:  ${{ secrets.DROPBOX_APP_SECRET }}}
          DROPBOX_REFRESH_TOKEN:  ${{ secrets.DROPBOX_REFRESH_TOKEN }}}
          GOOGLE_SERVICE : ${{ secrets.GOOGLE_SERVICE }}}
        run: python scripts/meds_tracker.py
        
      - name: Upload debug logs (if script fails)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
           name: debug-logs
           path: debug.log

     
