name: secrets check

on:
  push:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the full repo is cloned

      - name: print secrets
        shell: bash  # Fix indentation here
        env:
          KEY: ${{ secrets.DROPBOX_APP_KEY }}  # Fix indentation here
        run: |
          echo "$KEY"  # Fix indentation here
